name: publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'yngvem'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        run: |
          python -m pip install --upgrade pip wheel pipx
          python -m pipx install poetry
      - name: install dependencies
        run: |
          poetry install
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: run tests and linter
        run: |
          poetry run pytest
          poetry run flake8 .
          poetry run black --check .
          poetry run isort -c .
      - name: deploy
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish -r test-pypi
          poetry publish -r pypi